name: BCLD FLOW

on:
  push:
    branches:
      - main
jobs:
  venorless-release:
    runs-on: ubuntu-22.04
    environment: release
    container:
      image: ubuntu:jammy
      options: --privileged
      env:
        BCLD_APP: ${{ vars.BCLD_APP }}
        BCLD_CFG_EDIT: ${{ vars.BCLD_CFG_EDIT }}
        BCLD_MODEL: ${{ vars.BCLD_MODEL }}
        BCLD_SECRET: ${{ secrets.BCLD_SECRET }}
        CLEAN_BOOTSTRAP: ${{ vars.CLEAN_BOOTSTRAP }}
        NULLFIX: ${{ vars.NULLFIX }}
      volumes:
        - /dev:/dev:ro
        - /run:/run:rw
        - /var/docker.sock:/var/docker.sock:ro
        - ${{ github.workspace }}:/project:rw
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        /usr/bin/apt-get update
        /usr/bin/apt-get upgrade -y
        /usr/bin/apt-get install -y $(cat /project/config/packages/BUILD)
    - name: Run BCLD build scripts
      run: |
        /usr/bin/bash -c /project/ISO-builder.sh
        /usr/bin/bash -c /project/IMG-builder.sh
        /usr/bin/bash -c /project/tools/NEXUS-deploy.sh
