name: BCLD FLOW

on:
  push:
    branches:
      - main
jobs:
  vendorless-release:
    runs-on: ubuntu-22.04
    environment: release
    container:
      image: ubuntu:jammy
      options: --privileged
      env:
        BCLD_APP: ${{ vars.BCLD_APP }}
        BCLD_CFG_EDIT: ${{ vars.BCLD_CFG_EDIT }}
        BCLD_MODEL: ${{ vars.BCLD_MODEL }}
        BCLD_SECRET: ${{ secrets.BCLD_SECRET }}
        CLEAN_BOOTSTRAP: ${{ vars.CLEAN_BOOTSTRAP }}
        NULLFIX: ${{ vars.NULLFIX }}
      volumes:
        - /dev:/dev:ro
        - /run:/run:rw
        - /var/docker.sock:/var/docker.sock:ro
        - ${{ github.workspace }}:/project:rw
    steps:
    - name: Checkout local repository
      uses: actions/checkout@v2
    - name: Manually downloading submodules...
      run: |
        /usr/bin/apt-get update
        /usr/bin/apt-get install -y git
        /usr/bin/mkdir -pv modules
        cd modules || exit
        /usr/bin/git clone https://github.com/bats-core/bats-core.git
        /usr/bin/git clone https://github.com/bats-core/bats-support.git
        /usr/bin/git clone https://github.com/bats-core/bats-assert.git
        cd - || exit
    - name: Install dependencies
      run: |
        /usr/bin/apt-get update
        /usr/bin/apt-get upgrade -y
        /usr/bin/apt-get install -y $(cat /project/config/packages/BUILD)
    - name: Run BCLD build script through BATS
      run: |
        /usr/bin/bash -c 'BCLD_MODEL=release ./test/BCLD-BATS.sh'
    - name: Run BCLD RepoMan to scan all packages after RELEASE
      run: |
        /usr/bin/bash -c 'POINTER_TYPE=o ./tools/bcld-repo-manager/repository_manager.sh'
    - name: Upload ShellCheck report
      uses: actions/upload-artifact@v2
      with:
        name: SHELL-REPORT
        path: /project/test/SHELL-REPORT.txt
    - name: Upload BATS-REPORT
      uses: actions/upload-artifact@v2
      with:
        name: BATS-REPORT
        path: /project/test/BATS-REPORT.txt
    - name: Upload RepoMan Software Bill of Materials
      uses: actions/upload-artifact@v2
      with:
        name: RepoMan SBOM
        path: /project/artifacts/*.md
    - name: Upload kernel image
      uses: actions/upload-artifact@v2
      with:
        name: BCLD Kernel
        path: /project/artifacts/vmlinuz
    - name: Upload BCLD Ramdisk
      uses: actions/upload-artifact@v2
      with:
        name: BCLD-RAMFS
        path: /project/artifacts/initrd
    - name: Upload BCLD-ISO
      uses: actions/upload-artifact@v2
      with:
        name: BCLD-ISO
        path: /project/artifacts/bcld.iso
    - name: Upload BCLD-IMG
      uses: actions/upload-artifact@v2
      with:
        name: BCLD-IMG
        path: /project/artifacts/*.img

